import type { Metadata } from "next";
import { Geist, Geist_Mono, Great_Vibes, Parisienne, Rouge_Script, Spectral } from "next/font/google";
import "./globals.css";

const spectral = Spectral({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-serif',
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  weight: "400",
  variable: '--font-great-vibes',
  subsets: ["latin"],
});

const rougeScript = Rouge_Script({
  weight: "400",
  variable: '--font-rouge',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${spectral.variable} ${greatVibes.variable} ${rougeScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
